name: Create release

inputs:
  gh-token:
    description: A token to perform REST API calls to GitHub
    required: true
  repository:
    description: The repository name including the org
    required: true
  tag-name:
    description: The tag to use for the release
    required: true

outputs:
  release-id:
    description: The ID of the release
    value: ${{ steps.create-release.outputs.release_id }}

runs:
  using: composite
  steps:
    - name: Create release
      id: create-release
      shell: bash
      run: |
        RELEASE_ID=`curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.gh-token }}" \
          "https://api.github.com/repos/${{ inputs.repository }}/releases" \
          -d '{"tag_name":"${{ inputs.tag-name }}","generate_release_notes":true}' | jq -r '.id'`
        echo "release_id=$RELEASE_ID" >> "$GITHUB_OUTPUT"
