name: Select Xcode

inputs:
  xcode-version:
    description: The version of Xcode to select
    required: true

runs:
  using: composite
  steps:
    - name: Select Xcode
      shell: bash
      run: |
        sudo xcode-select \
          -s /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer
